export interface VoiceNavigationRoute {
  id: string;
  path: string;
  name: {
    en: string;
    ta: string;
    hi: string;
    te: string;
    ml: string;
    kn: string;
  };
  category: 'core' | 'care' | 'records' | 'services' | 'system';
  icon: string;
}

export const VOICE_NAVIGATION_ROUTES: VoiceNavigationRoute[] = [
  {
    id: 'dashboard',
    path: '/dashboard',
    name: {
      en: 'Dashboard',
      ta: 'முகப்பு',
      hi: 'डैशबोर्ड',
      te: 'డ్యాష్‌బోర్డ్',
      ml: 'ഡാഷ്‌ബോർഡ്',
      kn: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    },
    category: 'core',
    icon: 'LayoutDashboard',
  },
  {
    id: 'health',
    path: '/health',
    name: {
      en: 'My Health',
      ta: 'என் உடல்நலம்',
      hi: 'मेरा स्वास्थ्य',
      te: 'నా ఆరోగ్యం',
      ml: 'എന്റെ ആരോഗ്യം',
      kn: 'ನನ್ನ ಆರೋಗ್ಯ',
    },
    category: 'core',
    icon: 'Heart',
  },
  {
    id: 'family',
    path: '/family',
    name: {
      en: 'Family Health',
      ta: 'குடும்ப நலம்',
      hi: 'परिवार स्वास्थ्य',
      te: 'కుటుంబ ఆరోగ్యం',
      ml: 'കുടുംബാരോഗ്യം',
      kn: 'ಕುಟುಂಬ ಆರೋಗ್ಯ',
    },
    category: 'core',
    icon: 'Users',
  },
  {
    id: 'medicines',
    path: '/medicines',
    name: {
      en: 'Medicines & Reminders',
      ta: 'மருந்துகள் மற்றும் நினைவூட்டல்',
      hi: 'दवाइयां और रिमाइंडर',
      te: 'మందులు మరియు రిమైండర్లు',
      ml: 'മരുന്നുകളും ഓർമ്മപ്പെടുത്തലുകളും',
      kn: 'ಔಷಧಿಗಳು ಮತ್ತು ಜ್ಞಾಪನೆಗಳು',
    },
    category: 'care',
    icon: 'Pill',
  },
  {
    id: 'records',
    path: '/records',
    name: {
      en: 'Medical Records',
      ta: 'மருத்துவ பதிவுகள்',
      hi: 'मेडिकल रिकॉर्ड',
      te: 'వైద్య రికార్డులు',
      ml: 'മെഡിക്കൽ റെക്കോർഡുകൾ',
      kn: 'ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು',
    },
    category: 'records',
    icon: 'FileText',
  },
  {
    id: 'report_scanner',
    path: '/report-scanner',
    name: {
      en: 'Health Reports & Scanner',
      ta: 'அறிக்கை ஸ்கேனர்',
      hi: 'रिपोर्ट स्कैनर',
      te: 'రిపోర్ట్ స్కానర్',
      ml: 'റിപ്പോർട്ട് സ്കാനർ',
      kn: 'ವರದಿ ಸ್ಕ್ಯಾನರ್',
    },
    category: 'records',
    icon: 'ScanLine',
  },
  {
    id: 'xray_viewer',
    path: '/xray-viewer',
    name: {
      en: 'X-Ray & Scans',
      ta: 'எக்ஸ்-ரே மற்றும் ஸ்கேன்',
      hi: 'एक्स-रे और स्कैन',
      te: 'ఎక్స్-రే మరియు స్కాన్‌లు',
      ml: 'എക്സ്-റേ & സ്കാനുകൾ',
      kn: 'ಎಕ್ಸ್-ರೇ ಮತ್ತು ಸ್ಕ್ಯಾನ್‌ಗಳು',
    },
    category: 'records',
    icon: 'Image',
  },
  {
    id: 'health_tests',
    path: '/health-tests',
    name: {
      en: 'Health Tests & Vitals',
      ta: 'ஆரோக்கிய பரிசோதனைகள்',
      hi: 'स्वास्थ्य परीक्षण',
      te: 'ఆరోగ్య పరీక్షలు',
      ml: 'ആരോഗ്യ പരിശോധനകൾ',
      kn: 'ಆರೋಗ್ಯ ಪರೀಕ್ಷೆಗಳು',
    },
    category: 'care',
    icon: 'Activity',
  },
  {
    id: 'vaccinations',
    path: '/vaccination',
    name: {
      en: 'Vaccinations',
      ta: 'தடுப்பூசி அட்டவணை',
      hi: 'टीकाकरण',
      te: 'టీకాలు',
      ml: 'കുത്തിവയ്പ്പുകൾ',
      kn: 'ಲಸಿಕೆಗಳು',
    },
    category: 'care',
    icon: 'Syringe',
  },
  {
    id: 'ai_assistant',
    path: '/ai',
    name: {
      en: 'AI Health Assistant',
      ta: 'மெடோரா AI உதவியாளர்',
      hi: 'मेडोरा AI सहायक',
      te: 'మెడోరా AI అసిస్టెంట్',
      ml: 'മെഡോറ AI സഹായി',
      kn: 'ಮೆಡೋರಾ AI ಸಹಾಯಕ',
    },
    category: 'core',
    icon: 'Bot',
  },
  {
    id: 'doctor_portal',
    path: '/doctor-portal',
    name: {
      en: 'Doctor Consultation',
      ta: 'மருத்துவர் ஆலோசனை',
      hi: 'डॉक्टर परामर्श',
      te: 'వైద్యుని సంప్రదింపు',
      ml: 'ഡോക്ടർ കൺസൾട്ടേഷൻ',
      kn: 'ವೈದ್ಯರ ಸಮಾಲೋಚನೆ',
    },
    category: 'services',
    icon: 'Stethoscope',
  },
  {
    id: 'doctor_summary',
    path: '/doctor-summary',
    name: {
      en: 'Doctor Summary',
      ta: 'மருத்துவ சுருக்கம்',
      hi: 'डॉक्टर सारांश',
      te: 'డాక్టర్ సారాంశం',
      ml: 'ഡോക്ടർ സംഗ്രഹം',
      kn: 'ವೈದ್ಯರ ಸಾರಾಂಶ',
    },
    category: 'records',
    icon: 'ClipboardList',
  },
  {
    id: 'appointments',
    path: '/appointments',
    name: {
      en: 'Appointments',
      ta: 'மருத்துவ சந்திப்புகள்',
      hi: 'अपॉइंटमेंट',
      te: 'అపాయింట్‌మెంట్లు',
      ml: 'അപ്പോയിന്റ്മെന്റുകൾ',
      kn: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    },
    category: 'services',
    icon: 'Calendar',
  },
  {
    id: 'call_history',
    path: '/call-history',
    name: {
      en: 'Call History',
      ta: 'அழைப்பு வரலாறு',
      hi: 'कॉल विवरण',
      te: 'కాల్ చరిత్ర',
      ml: 'കോൾ ഹിസ്റ്ററി',
      kn: 'ಕರೆ ಇತಿಹಾಸ',
    },
    category: 'services',
    icon: 'PhoneCall',
  },
  {
    id: 'emergency',
    path: '/emergency',
    name: {
      en: 'Emergency Help',
      ta: 'அவசர உதவி',
      hi: 'आपातकालीन सहायता',
      te: 'అత్యవసర సహాయం',
      ml: 'അടിയന്തര സഹായം',
      kn: 'ತುರ್ತು ಸಹಾಯ',
    },
    category: 'services',
    icon: 'ShieldAlert',
  },
  {
    id: 'hospitals',
    path: '/hospitals',
    name: {
      en: 'Nearby Hospitals',
      ta: 'அருகிலுள்ள மருத்துவமனைகள்',
      hi: 'नजदीकी अस्पताल',
      te: 'సమీప ఆసుపత్రులు',
      ml: 'സമീപത്തെ ആശുപത്രികൾ',
      kn: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು',
    },
    category: 'services',
    icon: 'Building2',
  },
  {
    id: 'transport',
    path: '/transport',
    name: {
      en: 'Emergency Transport & Ambulance',
      ta: 'ஆம்புலன்ஸ் & போக்குவரத்து',
      hi: 'एम्बुलेंस और वाहन',
      te: 'అంబులెన్స్ & రవాణా',
      ml: 'ആംബുലൻസ് & ഗതാഗതം',
      kn: 'ಆಂಬ್ಯುಲೆನ್ಸ್ ಮತ್ತು ಸಾರಿಗೆ',
    },
    category: 'services',
    icon: 'Ambulance',
  },
  {
    id: 'schemes',
    path: '/schemes',
    name: {
      en: 'Government Schemes',
      ta: 'அரசு நலத்திட்டங்கள்',
      hi: 'सरकारी स्वास्थ्य योजनाएं',
      te: 'ప్రభుత్వ పథకాలు',
      ml: 'സർക്കാർ പദ്ധതികൾ',
      kn: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    },
    category: 'services',
    icon: 'Landmark',
  },
  {
    id: 'education',
    path: '/education',
    name: {
      en: 'Health Education',
      ta: 'சுகாதார வழிகாட்டல்',
      hi: 'स्वास्थ्य शिक्षा',
      te: 'ఆరోగ్య విద్య',
      ml: 'ആരോഗ്യ വിദ്യാഭ്യാസം',
      kn: 'ಆರೋಗ್ಯ ಶಿಕ್ಷಣ',
    },
    category: 'services',
    icon: 'GraduationCap',
  },
  {
    id: 'maternity',
    path: '/maternity',
    name: {
      en: 'Maternity Care',
      ta: 'தாய்மை நலம்',
      hi: 'मातृत्व देखभाल',
      te: 'గర్భధారణ సంరక్షణ',
      ml: 'ഗർഭകാല പരിചരണം',
      kn: 'ತಾಯ್ತನದ ಆರೈಕೆ',
    },
    category: 'care',
    icon: 'Baby',
  },
  {
    id: 'newborn',
    path: '/newborn',
    name: {
      en: 'Newborn Care',
      ta: 'பச்சிளம் குழந்தை நலம்',
      hi: 'नवजात शिशु देखभाल',
      te: 'నవజాత శిశు సంరక్షణ',
      ml: 'നവജാതശിശു പരിചരണം',
      kn: 'ನವಜಾತ ಶಿಶು ಆರೈಕೆ',
    },
    category: 'care',
    icon: 'Smile',
  },
  {
    id: 'elderly',
    path: '/elderly',
    name: {
      en: 'Elderly Care',
      ta: 'முதியோர் பராமரிப்பு',
      hi: 'बुजुर्गों की देखभाल',
      te: 'వృద్ధుల సంరక్షణ',
      ml: 'മുതിർന്നവരുടെ പരിചരണം',
      kn: 'ಹಿರಿಯರ ಆರೈಕೆ',
    },
    category: 'care',
    icon: 'UserCheck',
  },
  {
    id: 'sms',
    path: '/sms',
    name: {
      en: 'SMS & Messaging',
      ta: 'குறுஞ்செய்தி தொடர்பு',
      hi: 'एसएमएस संचार',
      te: 'ఎస్ఎంఎస్ కమ్యూనికేషన్',
      ml: 'എസ്എംഎസ് ആശയവിനിമയം',
      kn: 'ಎಸ್ಎಂಎಸ್ ಸಂವಹನ',
    },
    category: 'services',
    icon: 'MessageSquare',
  },
  {
    id: 'ussd',
    path: '/ussd',
    name: {
      en: 'USSD Basic Phone (*123#)',
      ta: 'USSD சாதாரண போன்',
      hi: 'यूएसएसडी साधारण फोन',
      te: 'యూఎస్‌ఎస్‌డీ బేసిక్ ఫోన్',
      ml: 'യുഎസ്എസ്ഡി ബേസിക് ഫോൺ',
      kn: 'ಯುಎಸ್‌ಎಸ್‌ಡಿ ಬೇಸಿಕ್ ಫೋನ್',
    },
    category: 'services',
    icon: 'Phone',
  },
  {
    id: 'village',
    path: '/village',
    name: {
      en: 'Village Health Dashboard',
      ta: 'கிராம சுகாதார பலகை',
      hi: 'ग्राम स्वास्थ्य डैशबोर्ड',
      te: 'గ్రామ ఆరోగ్య డాష్‌బోర్డ్',
      ml: 'ഗ്രാമ ആരോഗ്യ ഡാഷ്‌ബോർഡ്',
      kn: 'ಗ್ರಾಮ ಆರೋಗ್ಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    },
    category: 'services',
    icon: 'MapPin',
  },
  {
    id: 'profile',
    path: '/profile',
    name: {
      en: 'User Profile',
      ta: 'பயனர் சுயவிவரம்',
      hi: 'उपयोगकर्ता प्रोफाइल',
      te: 'యూజర్ ప్రొఫైల్',
      ml: 'പ്രൊഫൈൽ',
      kn: 'ಪ್ರೊಫೈಲ್',
    },
    category: 'system',
    icon: 'User',
  },
  {
    id: 'settings',
    path: '/settings',
    name: {
      en: 'Settings',
      ta: 'அமைப்புகள்',
      hi: 'सेटिंग्स',
      te: 'సెట్టింగ్‌లు',
      ml: 'ക്രമീകരണങ്ങൾ',
      kn: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    },
    category: 'system',
    icon: 'Settings',
  },
  {
    id: 'help',
    path: '/help',
    name: {
      en: 'Help & Guide',
      ta: 'உதவி வழிகாட்டி',
      hi: 'सहायता एवं निर्देश',
      te: 'సహాయం & మార్గదర్శి',
      ml: 'സഹായം & വഴികാട്ടി',
      kn: 'ಸಹಾಯ ಮತ್ತು ಮಾರ್ಗದರ್ಶಿ',
    },
    category: 'system',
    icon: 'HelpCircle',
  },
  {
    id: 'faq',
    path: '/faq',
    name: {
      en: 'Frequently Asked Questions',
      ta: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      hi: 'अक्सर पूछे जाने वाले सवाल',
      te: 'తరచుగా అడిగే ప్రశ్నలు',
      ml: 'പതിവുചോദ്യങ്ങൾ',
      kn: 'ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು',
    },
    category: 'system',
    icon: 'BookOpen',
  },
];
