import { VoiceNavigationIntent, VoiceNavigationRoute } from './voiceNavigationTypes';

/**
 * Centralized intent-to-path route map.
 * Guaranteed to match actual Medora routes.
 */
export const VOICE_NAVIGATION_ROUTES: Record<VoiceNavigationIntent, string> = {
  DASHBOARD: '/dashboard',
  MY_HEALTH: '/health',
  FAMILY_HEALTH: '/family',
  MEDICAL_RECORDS: '/records',
  MEDICINES: '/medicines',
  VACCINATIONS: '/vaccination',
  HEALTH_TESTS: '/health-tests',
  HEALTH_REPORTS: '/report-scanner',
  REPORT_SCANNER: '/report-scanner',
  XRAY: '/xray-viewer',
  AI_ASSISTANT: '/ai',
  DOCTOR_CONSULTATION: '/doctor-portal',
  DOCTOR_SUMMARY: '/doctor-summary',
  APPOINTMENTS: '/appointments',
  EMERGENCY: '/emergency',
  NEARBY_HOSPITALS: '/hospitals',
  GOVERNMENT_SCHEMES: '/schemes',
  HEALTH_EDUCATION: '/education',
  SMS_COMMUNICATION: '/sms',
  USSD: '/ussd',
  SETTINGS: '/settings',
  LANGUAGE: '/language-bridge',
  FAMILY: '/family',
  ELDERLY_CARE: '/elderly',
  CHILD_CARE: '/childcare',
  PREGNANCY: '/maternity',
  NEWBORN_CARE: '/newborn',
  NEW_MOTHER_CARE: '/maternity',
};

export const VOICE_NAVIGATION_ROUTE_LIST: VoiceNavigationRoute[] = [
  {
    id: 'dashboard',
    intent: 'DASHBOARD',
    path: '/dashboard',
    name: {
      en: 'Dashboard',
      ta: 'முகப்பு',
      hi: 'डैशबोर्ड',
      te: 'డ్యాష్‌బోర్డ్',
      ml: 'ഡാഷ്‌ബോർഡ്',
      kn: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    },
    category: 'core',
    icon: 'LayoutDashboard',
  },
  {
    id: 'health',
    intent: 'MY_HEALTH',
    path: '/health',
    name: {
      en: 'My Health',
      ta: 'என் உடல்நலம்',
      hi: 'मेरा स्वास्थ्य',
      te: 'నా ఆరోగ్యం',
      ml: 'എന്റെ ആരോഗ്യം',
      kn: 'ನನ್ನ ಆರೋಗ್ಯ',
    },
    category: 'core',
    icon: 'Heart',
  },
  {
    id: 'family',
    intent: 'FAMILY_HEALTH',
    path: '/family',
    name: {
      en: 'Family Health',
      ta: 'குடும்ப நலம்',
      hi: 'परिवार स्वास्थ्य',
      te: 'కుటుంబ ఆరోగ్యం',
      ml: 'കുടുംബാരോഗ്യം',
      kn: 'ಕುಟುಂಬ ಆರೋಗ್ಯ',
    },
    category: 'core',
    icon: 'Users',
  },
  {
    id: 'medicines',
    intent: 'MEDICINES',
    path: '/medicines',
    name: {
      en: 'Medicines & Reminders',
      ta: 'மருந்துகள் மற்றும் நினைவூட்டல்',
      hi: 'दवाइयां और रिमाइंडर',
      te: 'మందులు మరియు రిమైండర్లు',
      ml: 'മരുന്നുകളും ഓർമ്മപ്പെടുത്തലുകളും',
      kn: 'ಔಷಧಿಗಳು ಮತ್ತು ಜ್ಞಾಪನೆಗಳು',
    },
    category: 'care',
    icon: 'Pill',
  },
  {
    id: 'records',
    intent: 'MEDICAL_RECORDS',
    path: '/records',
    name: {
      en: 'Medical Records',
      ta: 'மருத்துவ பதிவுகள்',
      hi: 'मेडिकल रिकॉर्ड',
      te: 'వైద్య రికార్డులు',
      ml: 'മെഡിക്കൽ റെക്കോർഡുകൾ',
      kn: 'ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು',
    },
    category: 'records',
    icon: 'FileText',
  },
  {
    id: 'report_scanner',
    intent: 'REPORT_SCANNER',
    path: '/report-scanner',
    name: {
      en: 'Health Reports & Scanner',
      ta: 'அறிக்கை ஸ்கேனர்',
      hi: 'रिपोर्ट स्कैनर',
      te: 'రిపోర్ట్ స్కానర్',
      ml: 'റിപ്പോർട്ട് സ്കാനർ',
      kn: 'ವರದಿ ಸ್ಕ್ಯಾನರ್',
    },
    category: 'records',
    icon: 'ScanLine',
  },
  {
    id: 'xray_viewer',
    intent: 'XRAY',
    path: '/xray-viewer',
    name: {
      en: 'X-Ray & Scans',
      ta: 'எக்ஸ்-ரே மற்றும் ஸ்கேன்',
      hi: 'एक्स-रे और स्कैन',
      te: 'ఎక్స్-రే మరియు స్కాన్‌లు',
      ml: 'എക്സ്-റേ & സ്കാനുകൾ',
      kn: 'ಎಕ್ಸ್-ರೇ ಮತ್ತು ಸ್ಕ್ಯಾನ್‌ಗಳು',
    },
    category: 'records',
    icon: 'Image',
  },
  {
    id: 'health_tests',
    intent: 'HEALTH_TESTS',
    path: '/health-tests',
    name: {
      en: 'Health Tests & Vitals',
      ta: 'ஆரோக்கிய பரிசோதனைகள்',
      hi: 'स्वास्थ्य परीक्षण',
      te: 'ఆరోగ్య పరీక్షలు',
      ml: 'ആരോഗ്യ പരിശോധനകൾ',
      kn: 'ಆರೋಗ್ಯ ಪರೀಕ್ಷೆಗಳು',
    },
    category: 'care',
    icon: 'Activity',
  },
  {
    id: 'vaccinations',
    intent: 'VACCINATIONS',
    path: '/vaccination',
    name: {
      en: 'Vaccinations',
      ta: 'தடுப்பூசி அட்டவணை',
      hi: 'टीकाकरण',
      te: 'టీకాలు',
      ml: 'കുത്തിവയ്പ്പുകൾ',
      kn: 'ಲಸಿಕೆಗಳು',
    },
    category: 'care',
    icon: 'Syringe',
  },
  {
    id: 'ai_assistant',
    intent: 'AI_ASSISTANT',
    path: '/ai',
    name: {
      en: 'AI Health Assistant',
      ta: 'மெடோரா AI உதவியாளர்',
      hi: 'मेडोरा AI सहायक',
      te: 'మెడోరా AI అసిస్టెంట్',
      ml: 'മെഡോറ AI സഹായി',
      kn: 'ಮೆಡೋರಾ AI ಸಹಾಯಕ',
    },
    category: 'core',
    icon: 'Bot',
  },
  {
    id: 'doctor_portal',
    intent: 'DOCTOR_CONSULTATION',
    path: '/doctor-portal',
    name: {
      en: 'Doctor Consultation',
      ta: 'மருத்துவர் ஆலோசனை',
      hi: 'डॉक्टर परामर्श',
      te: 'వైద్యుని సంప్రదింపు',
      ml: 'ഡോക്ടർ കൺസൾട്ടേഷൻ',
      kn: 'ವೈದ್ಯರ ಸಮಾಲೋಚನೆ',
    },
    category: 'services',
    icon: 'Stethoscope',
  },
  {
    id: 'doctor_summary',
    intent: 'DOCTOR_SUMMARY',
    path: '/doctor-summary',
    name: {
      en: 'Doctor Summary',
      ta: 'மருத்துவ சுருக்கம்',
      hi: 'डॉक्टर सारांश',
      te: 'డాక్టర్ సారాంశం',
      ml: 'ഡോക്ടർ സംഗ്രഹം',
      kn: 'ವೈದ್ಯರ ಸಾರಾಂಶ',
    },
    category: 'records',
    icon: 'ClipboardList',
  },
  {
    id: 'appointments',
    intent: 'APPOINTMENTS',
    path: '/appointments',
    name: {
      en: 'Appointments',
      ta: 'மருத்துவ சந்திப்புகள்',
      hi: 'अपॉइंटमेंट',
      te: 'అపాయింట్‌మెంట్లు',
      ml: 'അപ്പോയിന്റ്മെന്റുകൾ',
      kn: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    },
    category: 'services',
    icon: 'Calendar',
  },
  {
    id: 'emergency',
    intent: 'EMERGENCY',
    path: '/emergency',
    name: {
      en: 'Emergency Help',
      ta: 'அவசர உதவி',
      hi: 'आपातकालीन सहायता',
      te: 'అత్యవసర సహాయం',
      ml: 'അടിയന്തര സഹായം',
      kn: 'ತುರ್ತು ಸಹಾಯ',
    },
    category: 'services',
    icon: 'ShieldAlert',
  },
  {
    id: 'hospitals',
    intent: 'NEARBY_HOSPITALS',
    path: '/hospitals',
    name: {
      en: 'Nearby Hospitals',
      ta: 'அருகிலுள்ள மருத்துவமனைகள்',
      hi: 'नजदीकी अस्पताल',
      te: 'సమీప ఆసుపత్రులు',
      ml: 'സമീപത്തെ ആശുപത്രികൾ',
      kn: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು',
    },
    category: 'services',
    icon: 'Building2',
  },
  {
    id: 'schemes',
    intent: 'GOVERNMENT_SCHEMES',
    path: '/schemes',
    name: {
      en: 'Government Schemes',
      ta: 'அரசு நலத்திட்டங்கள்',
      hi: 'सरकारी स्वास्थ्य योजनाएं',
      te: 'ప్రభుత్వ పథకాలు',
      ml: 'സർക്കാർ പദ്ധതികൾ',
      kn: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    },
    category: 'services',
    icon: 'Landmark',
  },
  {
    id: 'education',
    intent: 'HEALTH_EDUCATION',
    path: '/education',
    name: {
      en: 'Health Education',
      ta: 'சுகாதார வழிகாட்டல்',
      hi: 'स्वास्थ्य शिक्षा',
      te: 'ఆరోగ్య విద్య',
      ml: 'ആരോഗ്യ വിദ്യാഭ്യാസം',
      kn: 'ಆರೋಗ್ಯ ಶಿಕ್ಷಣ',
    },
    category: 'services',
    icon: 'GraduationCap',
  },
  {
    id: 'maternity',
    intent: 'PREGNANCY',
    path: '/maternity',
    name: {
      en: 'Maternity Care',
      ta: 'தாய்மை நலம்',
      hi: 'मातृत्व देखभाल',
      te: 'గర్భధారణ సంరక్షణ',
      ml: 'ഗർഭകാല പരിചരണം',
      kn: 'ತಾಯ್ತನದ ಆರೈಕೆ',
    },
    category: 'care',
    icon: 'Baby',
  },
  {
    id: 'newborn',
    intent: 'NEWBORN_CARE',
    path: '/newborn',
    name: {
      en: 'Newborn Care',
      ta: 'பச்சிளம் குழந்தை நலம்',
      hi: 'नवजात शिशु देखभाल',
      te: 'నవజాత శిశు సంరక్షణ',
      ml: 'നവജാതശിശു പരിചരണം',
      kn: 'ನವಜಾತ ಶಿಶು ಆರೈಕೆ',
    },
    category: 'care',
    icon: 'Smile',
  },
  {
    id: 'childcare',
    intent: 'CHILD_CARE',
    path: '/childcare',
    name: {
      en: 'Child Care',
      ta: 'குழந்தை நலம்',
      hi: 'बाल देखभाल',
      te: 'పిల్లల సంరక్షణ',
      ml: 'കുട്ടികളുടെ പരിചരണം',
      kn: 'ಮಕ್ಕಳ ಆರೈಕೆ',
    },
    category: 'care',
    icon: 'Smile',
  },
  {
    id: 'elderly',
    intent: 'ELDERLY_CARE',
    path: '/elderly',
    name: {
      en: 'Elderly Care',
      ta: 'முதியோர் பராமரிப்பு',
      hi: 'बुजुर्गों की देखभाल',
      te: 'వృద్ధుల సంరక్షణ',
      ml: 'മുതിർന്നവരുടെ പരിചരണം',
      kn: 'ಹಿರಿಯರ ಆರೈಕೆ',
    },
    category: 'care',
    icon: 'UserCheck',
  },
  {
    id: 'sms',
    intent: 'SMS_COMMUNICATION',
    path: '/sms',
    name: {
      en: 'SMS & Messaging',
      ta: 'குறுஞ்செய்தி தொடர்பு',
      hi: 'एसएमएस संचार',
      te: 'ఎస్ఎంఎస్ కమ్యూనికేషన్',
      ml: 'എസ്എംഎസ് ആശയവിനിമയം',
      kn: 'ಎಸ್ಎಂಎಸ್ ಸಂವಹನ',
    },
    category: 'services',
    icon: 'MessageSquare',
  },
  {
    id: 'ussd',
    intent: 'USSD',
    path: '/ussd',
    name: {
      en: 'USSD Basic Phone (*123#)',
      ta: 'USSD சாதாரண போன்',
      hi: 'यूएसएसडी साधारण फोन',
      te: 'యూఎస్‌ఎస్‌డీ బేసిక్ ఫోన్',
      ml: 'യുഎസ്എസ്ഡി ബേസിക് ഫോൺ',
      kn: 'ಯುಎಸ್‌ಎಸ್‌ಡಿ ಬೇಸಿಕ್ ಫೋನ್',
    },
    category: 'services',
    icon: 'Phone',
  },
  {
    id: 'settings',
    intent: 'SETTINGS',
    path: '/settings',
    name: {
      en: 'Settings',
      ta: 'அமைப்புகள்',
      hi: 'सेटिंग्स',
      te: 'సెట్టింగ్‌లు',
      ml: 'ക്രമീകരണങ്ങൾ',
      kn: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    },
    category: 'system',
    icon: 'Settings',
  },
  {
    id: 'language',
    intent: 'LANGUAGE',
    path: '/language-bridge',
    name: {
      en: 'Language Bridge',
      ta: 'மொழி பாலம்',
      hi: 'भाषा सेतु',
      te: 'భాషా వారధి',
      ml: 'ഭാഷാ പാലം',
      kn: 'ಭಾಷಾ ಸೇತು',
    },
    category: 'system',
    icon: 'Languages',
  },
];

export function getRouteByIntent(intent: VoiceNavigationIntent): VoiceNavigationRoute | undefined {
  return VOICE_NAVIGATION_ROUTE_LIST.find((r) => r.intent === intent);
}

export function getPathByIntent(intent: VoiceNavigationIntent): string {
  return VOICE_NAVIGATION_ROUTES[intent] || '/dashboard';
}
